//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.19 at 01:20:51 AM IDT 
//


package semulator.logic.xml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the semulator.logic.xml.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SVariable_QNAME = new QName("", "S-Variable");
    private final static QName _SLabel_QNAME = new QName("", "S-Label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: semulator.logic.xml.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SProgram }
     * 
     */
    public SProgram createSProgram() {
        return new SProgram();
    }

    /**
     * Create an instance of {@link SInstructions }
     * 
     */
    public SInstructions createSInstructions() {
        return new SInstructions();
    }

    /**
     * Create an instance of {@link SInstruction }
     * 
     */
    public SInstruction createSInstruction() {
        return new SInstruction();
    }

    /**
     * Create an instance of {@link SInstructionArguments }
     * 
     */
    public SInstructionArguments createSInstructionArguments() {
        return new SInstructionArguments();
    }

    /**
     * Create an instance of {@link SInstructionArgument }
     * 
     */
    public SInstructionArgument createSInstructionArgument() {
        return new SInstructionArgument();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "S-Variable")
    public JAXBElement<String> createSVariable(String value) {
        return new JAXBElement<String>(_SVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "S-Label")
    public JAXBElement<String> createSLabel(String value) {
        return new JAXBElement<String>(_SLabel_QNAME, String.class, null, value);
    }

}
