//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.19 at 01:20:51 AM IDT 
//


package semulator.logic.xml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}S-Variable"/&gt;
 *         &lt;element ref="{}S-Instruction-Arguments" minOccurs="0"/&gt;
 *         &lt;element ref="{}S-Label" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="basic"/&gt;
 *             &lt;enumeration value="synthetic"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="name" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="NEUTRAL"/&gt;
 *             &lt;enumeration value="INCREASE"/&gt;
 *             &lt;enumeration value="DECREASE"/&gt;
 *             &lt;enumeration value="JUMP_NOT_ZERO"/&gt;
 *             &lt;enumeration value="ZERO_VARIABLE"/&gt;
 *             &lt;enumeration value="ASSIGNMENT"/&gt;
 *             &lt;enumeration value="GOTO_LABEL"/&gt;
 *             &lt;enumeration value="CONSTANT_ASSIGNMENT"/&gt;
 *             &lt;enumeration value="JUMP_ZERO"/&gt;
 *             &lt;enumeration value="JUMP_EQUAL_CONSTANT"/&gt;
 *             &lt;enumeration value="JUMP_EQUAL_VARIABLE"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "S-Instruction")
public class SInstruction {

    @XmlElement(name = "S-Variable", required = true)
    protected String sVariable;
    @XmlElement(name = "S-Instruction-Arguments")
    protected SInstructionArguments sInstructionArguments;
    @XmlElement(name = "S-Label")
    protected String sLabel;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the sVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSVariable() {
        return sVariable;
    }

    /**
     * Sets the value of the sVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSVariable(String value) {
        this.sVariable = value;
    }

    /**
     * Gets the value of the sInstructionArguments property.
     * 
     * @return
     *     possible object is
     *     {@link SInstructionArguments }
     *     
     */
    public SInstructionArguments getSInstructionArguments() {
        return sInstructionArguments;
    }

    /**
     * Sets the value of the sInstructionArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SInstructionArguments }
     *     
     */
    public void setSInstructionArguments(SInstructionArguments value) {
        this.sInstructionArguments = value;
    }

    /**
     * Gets the value of the sLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLabel() {
        return sLabel;
    }

    /**
     * Sets the value of the sLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLabel(String value) {
        this.sLabel = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
